### ISSUE TITLE
not return an error to the caller

### ISSUE THREAD

**Issue by fahmifan** [aldy505/phc-crypto#1]
I think, we should always return an error to the caller

What is the reason to not return it in this code ?
```
decodedHash, err := hex.DecodeString(deserialize.Hash)
if err != nil {
    return false, nil
}
```

refer to: https://github.com/aldy505/phc-crypto/blob/83ad78b3d95edad3e5df9dfc40acdb0d19a4da5b/bcrypt/bcrypt.go#L43

**Comment by aldy505** [comment]
Whoops. My bad! Thanks for pointing that out. Should be fixed on 5c8e01d
