### ISSUE TITLE
Hi couple years ago you worked on Fairbrix token can you provide me some for development?

### ISSUE THREAD

**Issue by potatodata** [aldy505/phc-crypto#4]

**Comment by aldy505** [comment]
No I didn't work for Fairbrix token

**Comment by potatodata** [comment]
<img width="1158" alt="Fairbrix" src="https://github.com/aldy505/phc-crypto/assets/148652460/0cdbd96b-3b45-436c-832a-2cbfa84f5fb2">

Isn't this you?

**Comment by aldy505** [comment]
Please read the whole document thoroughly. It's quoted from Wikipedia. Based on your activity on GitHub, this is not the place to ask for free crypto coins, please do that somewhere else.
